# Engine settings
clearcolorbuffer	1
clearcolor	0.0000000 0.0000000 0.0000000 0.0000000
ambient	1.0000000 1.0000000 1.0000000 0.0000000
fog	0
fogcolor	0.0000000 0.0000000 0.0000000 0.0000000
fogmode	exp
fogstart	100.0000000
fogend	500.0000000
fogdensity	1.0000000


# Object creation

new sivicPackage audi-A4_Dynamic
new sivicPackage radarLevel1
new sivicPackage ground_checker


# Object configuration

# Object _DefaultRenderer with type mgAccurateRenderer
_DefaultRenderer.SetDisabled	0
_DefaultRenderer.SetHidden	1
_DefaultRenderer.SetPersistent	1
_DefaultRenderer.SetWireframe 0
_DefaultRenderer.SetNoTextures 0
_DefaultRenderer.SetClampVertexColor 0
_DefaultRenderer.SetClampFragmentColor 0

# Object editor with type sivicPackage
editor.SetDisabled	0
editor.SetHidden	1
editor.SetPersistent	1
editor.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object editor/cam with type sivicCamera
editor/cam.SetPeriod 0.0400000
editor/cam.SetOMGDDSEnabled false
editor/cam.SetFileName cam
editor/cam.SetExtension .cap
editor/cam.Off 
editor/cam.SetRecordEnabled false
editor/cam.SetExportFormat tsv
editor/cam.SetDisabled	0
editor/cam.SetPersistent	1
editor/cam.SetLocalPosition	-11.1137209 -0.2713614 11.9791451
editor/cam.SetLocalRotation	33.2803535 -38.2406807 -92.3211746
#editor/cam.SetLocalRotationAngles	45.0000000 -0.0000034 -97.9347610
editor/cam.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/cam.SetFrustum	-0.1258035 0.1258035 -0.0767327 0.0767327 0.1000000 5000.0000000
editor/cam.SetRenderSize 1187 724
editor/cam.SetRenderer editor/ren
editor/cam.SetCaptureFileName MGEngine
editor/cam.SetClearColorBufferRegion 1
editor/cam.SetColorFormat rgb8
editor/cam.SetDepthFormat DEPTH_24
editor/cam.SetMultiSamples 4
editor/cam.SetCorrectDistortion 1
editor/cam.SetEnableIntegration 0
editor/cam.SetExposureTime 0.0400000
editor/cam.SetExposureSampling 0.0050000
editor/cam.SetMatrixSize 2.6666000 2.0000000
editor/cam.SetFocalLength 1.3032253
editor/cam.SetZNear 0.1000000
editor/cam.SetZFar 5000.0000000
editor/cam.SetCollectDepthImage off
editor/cam.SetDepthImageRange 1000
editor/cam.SetDepthImageResolution 1
editor/cam.SetImageType RGB24
editor/cam.SetNbEffectiveBits 8
editor/cam.SetRecordFormat bmp
editor/cam.SetPNGCompression png_1
editor/cam.SetModeCorrection off
editor/cam.SetCollectLabelImage 0
editor/cam.SetOccludeLabels 1

# Object editor/view with type sivicCameraViewport
editor/view.SetDisabled	0
editor/view.SetPersistent	1
editor/view.SetAutoResize 1
editor/view.SetViewport 0.0000000% 0.0000000% 100.0000000% 100.0000000%
editor/view.SetCamera editor/cam
editor/view.SetColorMask 1 1 1
editor/view.SetForceCameraResize 1
editor/view.SetMinDepthRange 0.0000000
editor/view.SetMaxDepthRange 100.0000000
editor/view.SetLookupTexture 

# Object editor/ren with type sivicEditorRenderer
editor/ren.SetDisabled	0
editor/ren.SetPersistent	1
editor/ren.SetWireframe 0
editor/ren.SetNoTextures 0
editor/ren.SetClampVertexColor 0
editor/ren.SetClampFragmentColor 0
editor/ren.SetShowGrid 1
editor/ren.SetGridMesh checker
editor/ren.SetShowAxes 1
editor/ren.SetAxesMesh repere
editor/ren.SetHighlight 1
editor/ren.SetHighlightColor 1.0000000 0.3000000 0.0000000 

# Object editor/cont with type mgPositionController
editor/cont.SetDisabled	0
editor/cont.SetPersistent	1
editor/cont.AttachTo editor/cam
editor/cont.SetXPosController	x_trans3
editor/cont.SetYPosController	y_trans3
editor/cont.SetZPosController	z_trans3
editor/cont.SetXRotController	x_rot3
editor/cont.SetYRotController	y_rot3
editor/cont.SetZRotController	z_rot3
editor/cont.SetTranslationSpeed	10.0000000
editor/cont.SetRotationSpeed	3.1415899
editor/cont.SetRealTime	on
editor/cont.SetMode Fly

# Object editor/tt with type mgTrackTo
editor/tt.SetDisabled	0
editor/tt.SetPersistent	1
editor/tt.ApplyTo editor/cam

# Object editor/_RendererPlugin_sivicBeaconReceiverDisplay with type sivicBeaconReceiverDisplay
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicBeaconTransmitterDisplay with type sivicBeaconTransmitterDisplay
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCameraDisplay with type sivicCameraDisplay
editor/_RendererPlugin_sivicCameraDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCameraDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCameraDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCameraDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicCarDisplay with type sivicCarDisplay
editor/_RendererPlugin_sivicCarDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCarDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCarDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCarDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCarDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCarDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicCarDisplay.SetShowPath 1
editor/_RendererPlugin_sivicCarDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicCarDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetShowMeanTurningRadiusFront 0
editor/_RendererPlugin_sivicCarDisplay.SetShowTurningFrontDeadZone 0
editor/_RendererPlugin_sivicCarDisplay.SetShowCollisionRaytrace 0

# Object editor/_RendererPlugin_sivicCommunicationDisplay with type sivicCommunicationDisplay
editor/_RendererPlugin_sivicCommunicationDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetShowAll 0
editor/_RendererPlugin_sivicCommunicationDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCompassDisplay with type sivicCompassDisplay
editor/_RendererPlugin_sivicCompassDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassDisplay.SetWireframe 1
editor/_RendererPlugin_sivicCompassDisplay.SetShowWind 1

# Object editor/_RendererPlugin_sivicCompassRoseDisplay with type sivicCompassRoseDisplay
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetWireframe 0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetShowWind 1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCompassPoint 8

# Object editor/_RendererPlugin_sivicDistanceObserverDisplay with type sivicDistanceObserverDisplay
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetWireframe 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowObjectIndicator 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowMeasurePoint 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetColor 0.0000000 0.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLineWidth 5.0000000

# Object editor/_RendererPlugin_sivicEventDisplay with type sivicEventDisplay
editor/_RendererPlugin_sivicEventDisplay.SetDisabled	0
editor/_RendererPlugin_sivicEventDisplay.SetPersistent	1
editor/_RendererPlugin_sivicEventDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicEventDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicEventDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicEventDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicEventDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicEventDisplay.SetShowAll 0
editor/_RendererPlugin_sivicEventDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay with type sivicExternalTrajectoryReaderDisplay
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPrecision 8
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPathColor 1.0000000 0.3300000 0.5000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPath 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicGPSDisplay with type sivicGPSDisplay
editor/_RendererPlugin_sivicGPSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicGPSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicGPSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicGPSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicGPSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicGPSDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicHumanDisplay with type sivicHumanDisplay
editor/_RendererPlugin_sivicHumanDisplay.SetDisabled	0
editor/_RendererPlugin_sivicHumanDisplay.SetPersistent	1
editor/_RendererPlugin_sivicHumanDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicHumanDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowPath 1
editor/_RendererPlugin_sivicHumanDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicHumanDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetShowWalkingZone 0

# Object editor/_RendererPlugin_sivicInclinometerDisplay with type sivicInclinometerDisplay
editor/_RendererPlugin_sivicInclinometerDisplay.SetDisabled	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetPersistent	1
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicLightSourceDisplay with type sivicLightSourceDisplay
editor/_RendererPlugin_sivicLightSourceDisplay.SetDisabled	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetPersistent	1
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetShowAll 0
editor/_RendererPlugin_sivicLightSourceDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRadarHUD with type sivicRadarHUD
editor/_RendererPlugin_sivicRadarHUD.SetDisabled	0
editor/_RendererPlugin_sivicRadarHUD.SetPersistent	1
editor/_RendererPlugin_sivicRadarHUD.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarHUD.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarHUD.SetCastShadows	0
editor/_RendererPlugin_sivicRadarHUD.SetRenderOrder	5.0000000
editor/_RendererPlugin_sivicRadarHUD.SetDoNotRender	0
editor/_RendererPlugin_sivicRadarHUD.SetLobePlot 1
editor/_RendererPlugin_sivicRadarHUD.SetLogDisplay 1
editor/_RendererPlugin_sivicRadarHUD.SetDisplayResolution 1.0000000

# Object editor/_RendererPlugin_sivicRadarSimpleDisplay with type sivicRadarSimpleDisplay
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicRangefinderDisplay with type sivicRangefinderDisplay
editor/_RendererPlugin_sivicRangefinderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetShowAll 1
editor/_RendererPlugin_sivicRangefinderDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRCSDisplay with type sivicRCSDisplay
editor/_RendererPlugin_sivicRCSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRCSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRCSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRCSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRCSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicRCSDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicTrajectoryDisplay with type sivicTrajectoryDisplay
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDisabled	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPersistent	1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPrecision 8
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPathColor 0.2000000 0.6000000 0.5000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPath 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicUltrasonicSensorDisplay with type sivicUltrasonicSensorDisplay
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDisabled	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetPersistent	1
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDoNotRender	0

# Object audi-A4_Dynamic with type sivicPackage
audi-A4_Dynamic.SetDisabled	0
audi-A4_Dynamic.SetLocalPosition	0.0000000 0.0000000 0.0000000
audi-A4_Dynamic.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic.SetPackageData	Audi-A4_Dynamic.zip

# Object audi-A4_Dynamic/vc with type sivicCarViewport
audi-A4_Dynamic/vc.SetPeriod 0.0400000
audi-A4_Dynamic/vc.SetOMGDDSEnabled false
audi-A4_Dynamic/vc.SetFileName vc
audi-A4_Dynamic/vc.SetExtension .cap
audi-A4_Dynamic/vc.Off 
audi-A4_Dynamic/vc.SetRecordEnabled false
audi-A4_Dynamic/vc.SetExportFormat tsv
audi-A4_Dynamic/vc.SetDisabled	0
audi-A4_Dynamic/vc.SetViewport 0 0 100 47
# Backgound color for audi-A4_Dynamic/vc: 
audi-A4_Dynamic/vc.SetTransparency true
audi-A4_Dynamic/vc.SetWatermark 0.0000000
audi-A4_Dynamic/vc.SetBackgroundColor 1.0000000 0.0000000 0.0000000 0.0000000
audi-A4_Dynamic/vc.SetPosition 0 0
audi-A4_Dynamic/vc.SetSize 100 47
audi-A4_Dynamic/vc.SetDigitWidth 0.1500000
audi-A4_Dynamic/vc.SetPositionUnit 0.6000000
audi-A4_Dynamic/vc.SetDataColor 0.0000000 0.0000000 0.0000000 1.0000000
audi-A4_Dynamic/vc.SetCar audi-A4_Dynamic/car

# Object audi-A4_Dynamic/chassis with type sivicMeshActor
audi-A4_Dynamic/chassis.AddProperty	VehicleModel	string	Audi_A4
audi-A4_Dynamic/chassis.AddProperty	VehicleType	string	car
audi-A4_Dynamic/chassis.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/chassis.SetDisabled	0
audi-A4_Dynamic/chassis.SetLocalPosition	-1.3300000 0.0000063 0.2918012
audi-A4_Dynamic/chassis.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/chassis.SetLocalRotationAngles	-0.0006482 0.0000941 0.0000000
audi-A4_Dynamic/chassis.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/chassis.SetCastShadows	0
audi-A4_Dynamic/chassis.SetRenderOrder	1.0000000
audi-A4_Dynamic/chassis.SetDoNotRender	0
audi-A4_Dynamic/chassis.SetMesh	A4/A4_Dynamic
audi-A4_Dynamic/chassis.SetCatchShadows	1
audi-A4_Dynamic/chassis.SetOccludeAmbient	0
audi-A4_Dynamic/chassis.SetCameraAligned	0

# Object audi-A4_Dynamic/fl with type sivicMeshActor
audi-A4_Dynamic/fl.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/fl.SetDisabled	0
audi-A4_Dynamic/fl.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/fl.SetLocalPosition	2.6600001 0.7500002 -0.0210408
audi-A4_Dynamic/fl.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/fl.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/fl.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/fl.SetCastShadows	0
audi-A4_Dynamic/fl.SetRenderOrder	1.0000000
audi-A4_Dynamic/fl.SetDoNotRender	0
audi-A4_Dynamic/fl.SetMesh	A4_wheel/left_wheel
audi-A4_Dynamic/fl.SetCatchShadows	1
audi-A4_Dynamic/fl.SetOccludeAmbient	0
audi-A4_Dynamic/fl.SetCameraAligned	0

# Object audi-A4_Dynamic/fr with type sivicMeshActor
audi-A4_Dynamic/fr.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/fr.SetDisabled	0
audi-A4_Dynamic/fr.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/fr.SetLocalPosition	2.6600001 -0.7499998 -0.0210578
audi-A4_Dynamic/fr.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/fr.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/fr.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/fr.SetCastShadows	0
audi-A4_Dynamic/fr.SetRenderOrder	1.0000000
audi-A4_Dynamic/fr.SetDoNotRender	0
audi-A4_Dynamic/fr.SetMesh	A4_wheel/right_wheel
audi-A4_Dynamic/fr.SetCatchShadows	1
audi-A4_Dynamic/fr.SetOccludeAmbient	0
audi-A4_Dynamic/fr.SetCameraAligned	0

# Object audi-A4_Dynamic/rl with type sivicMeshActor
audi-A4_Dynamic/rl.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/rl.SetDisabled	0
audi-A4_Dynamic/rl.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/rl.SetLocalPosition	0.0000000 0.7500002 -0.0210452
audi-A4_Dynamic/rl.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/rl.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/rl.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/rl.SetCastShadows	0
audi-A4_Dynamic/rl.SetRenderOrder	1.0000000
audi-A4_Dynamic/rl.SetDoNotRender	0
audi-A4_Dynamic/rl.SetMesh	A4_wheel/left_wheel
audi-A4_Dynamic/rl.SetCatchShadows	1
audi-A4_Dynamic/rl.SetOccludeAmbient	0
audi-A4_Dynamic/rl.SetCameraAligned	0

# Object audi-A4_Dynamic/rr with type sivicMeshActor
audi-A4_Dynamic/rr.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/rr.SetDisabled	0
audi-A4_Dynamic/rr.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/rr.SetLocalPosition	0.0000000 -0.7499998 -0.0210621
audi-A4_Dynamic/rr.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/rr.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/rr.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/rr.SetCastShadows	0
audi-A4_Dynamic/rr.SetRenderOrder	1.0000000
audi-A4_Dynamic/rr.SetDoNotRender	0
audi-A4_Dynamic/rr.SetMesh	A4_wheel/right_wheel
audi-A4_Dynamic/rr.SetCatchShadows	1
audi-A4_Dynamic/rr.SetOccludeAmbient	0
audi-A4_Dynamic/rr.SetCameraAligned	0

# Object audi-A4_Dynamic/CollisionModel with type sivicMeshActor
audi-A4_Dynamic/CollisionModel.AddProperty	layers	mgLayers	16777215
audi-A4_Dynamic/CollisionModel.SetDisabled	0
audi-A4_Dynamic/CollisionModel.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/CollisionModel.SetLocalPosition	0.0000000 0.0000000 0.0000000
audi-A4_Dynamic/CollisionModel.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/CollisionModel.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/CollisionModel.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/CollisionModel.SetCastShadows	0
audi-A4_Dynamic/CollisionModel.SetRenderOrder	1.0000000
audi-A4_Dynamic/CollisionModel.SetDoNotRender	1
audi-A4_Dynamic/CollisionModel.SetMesh	audi_A4_rcs/audi_A4_rcs
audi-A4_Dynamic/CollisionModel.SetCatchShadows	1
audi-A4_Dynamic/CollisionModel.SetOccludeAmbient	0
audi-A4_Dynamic/CollisionModel.SetCameraAligned	0

# Object audi-A4_Dynamic/RCS with type sivicRCS
audi-A4_Dynamic/RCS.SetDisabled	0
audi-A4_Dynamic/RCS.MakeChildOf audi-A4_Dynamic/chassis
audi-A4_Dynamic/RCS.SetLocalPosition	1.5000000 0.0000000 0.0000000
audi-A4_Dynamic/RCS.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi-A4_Dynamic/RCS.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi-A4_Dynamic/RCS.SetLocalScale	1.0000000 1.0000000 1.0000000
audi-A4_Dynamic/RCS.SetCollisionModel audi-A4_Dynamic/CollisionModel
audi-A4_Dynamic/RCS.ClearLobes
audi-A4_Dynamic/RCS.AddLobe 1.0000000	1.0000000	-1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 -1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 -1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
audi-A4_Dynamic/RCS.SetRCSData biw_work3_monostatic.rcs
audi-A4_Dynamic/RCS.SetPolicy table
audi-A4_Dynamic/RCS.SetSymetryX none
audi-A4_Dynamic/RCS.SetSymetryY none
audi-A4_Dynamic/RCS.SetSymetryZ none

# Object audi-A4_Dynamic/car with type sivicCar
audi-A4_Dynamic/car.AddProperty	ColorLabel	mgColor	255 0 0 255
audi-A4_Dynamic/car.SetDisabled	0
audi-A4_Dynamic/car.SetPeriod 0.0050000
audi-A4_Dynamic/car.SetOMGDDSEnabled false
# SetCarDescriptionData will be use to load resource used to override car body color.
audi-A4_Dynamic/car.SetCarBodyColorMaterialData body_color_material.conf
audi-A4_Dynamic/car.SetCarBodyColor Black
# Meshes for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetChassis audi-A4_Dynamic/chassis
audi-A4_Dynamic/car.SetWheelFL audi-A4_Dynamic/fl
audi-A4_Dynamic/car.SetWheelFR audi-A4_Dynamic/fr
audi-A4_Dynamic/car.SetWheelRL audi-A4_Dynamic/rl
audi-A4_Dynamic/car.SetWheelRR audi-A4_Dynamic/rr
audi-A4_Dynamic/car.SetEnableWheelScale false
# Controllers for audi-A4_Dynamic/car (analogical inputs): 
audi-A4_Dynamic/car.SetAccCtrl car1_ThrottlePedal
audi-A4_Dynamic/car.SetAccCtrlDuration 0.0001000
audi-A4_Dynamic/car.SetClutchCtrl car1_ClutchPedal
audi-A4_Dynamic/car.SetClutchCtrlDuration 0.0001000
audi-A4_Dynamic/car.SetBrakeCtrl car1_BrakePedal
audi-A4_Dynamic/car.SetBrakeCtrlDuration 0.0001000
audi-A4_Dynamic/car.SetSteerCtrl car1_SteeringWheelAngle
audi-A4_Dynamic/car.SetSteerCtrlDuration 0.0001000
# Controllers for audi-A4_Dynamic/car (binary inputs): 
audi-A4_Dynamic/car.SetUpGearCtrl car1_UpGear
audi-A4_Dynamic/car.SetDownGearCtrl car1_DownGear
audi-A4_Dynamic/car.SetUpKeyCtrl car1_UpKey
audi-A4_Dynamic/car.SetDownKeyCtrl car1_DownKey
audi-A4_Dynamic/car.SetStopCtrl car1_Stop
audi-A4_Dynamic/car.SetUseAdaptativeSteeringSpeed 1
audi-A4_Dynamic/car.SetUseRoadAsGround 1
audi-A4_Dynamic/car.SetUseStopOnObstacles 1
audi-A4_Dynamic/car.SetMass 1374.0000000
audi-A4_Dynamic/car.SetWheelsSpacing 1.3300000 1.3300000 0.7500000 0.7500000
#audi-A4_Dynamic/car.SetWheelbase 2.6600001
#audi-A4_Dynamic/car.SetFrontTrack 1.5000000
#audi-A4_Dynamic/car.SetRearTrack 1.5000000
audi-A4_Dynamic/car.SetIgnitionKey 1
audi-A4_Dynamic/car.SetGearShift 1
audi-A4_Dynamic/car.SetAutoClutch 1
audi-A4_Dynamic/car.SetPosition -0.0000000 0.0000063 0.5625486
audi-A4_Dynamic/car.SetAngle -0.0006482 0.0000941 0.0000000
audi-A4_Dynamic/car.SetGroundTireAltitude 0.0000000 0.0000000 0.0000000 0.0000000
# Shock absorbers parameters for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetShockAbsorberFL 20000.0000000 6000.0000000
audi-A4_Dynamic/car.SetShockAbsorberFR 20000.0000000 6000.0000000
audi-A4_Dynamic/car.SetShockAbsorberRL 20000.0000000 6000.0000000
audi-A4_Dynamic/car.SetShockAbsorberRR 20000.0000000 6000.0000000
# Wheels parameters for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetWheelsHeight 0.0400000 0.0300000
audi-A4_Dynamic/car.SetTireCode 225.0000000 18.1102009 18.1102009
audi-A4_Dynamic/car.SetTireGripFR 0.9000000
audi-A4_Dynamic/car.SetTireGripFL 0.9000000
audi-A4_Dynamic/car.SetTireGripRR 0.9000000
audi-A4_Dynamic/car.SetTireGripRL 0.9000000
# Masses and inertia for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetCarMasses 1500.0000000 1500.0000000 1340.0000000
audi-A4_Dynamic/car.SetCarMomentOfInertia 305.0000000 2000.0000000 2454.0000000
audi-A4_Dynamic/car.SetTireMass 18.0000000
audi-A4_Dynamic/car.SetTireMomentOfInertia 1.2825000
audi-A4_Dynamic/car.SetMaxOrderAcc 790.0000000
audi-A4_Dynamic/car.SetMaxOrderBrk 1250.0000000
audi-A4_Dynamic/car.SetMaxOrderSteer 0.5200000
audi-A4_Dynamic/car.SetMaxSpeedSteer 0.7853982
audi-A4_Dynamic/car.SetBrakeTorqueDistributionFL 0.6000000
audi-A4_Dynamic/car.SetBrakeTorqueDistributionFR 0.6000000
audi-A4_Dynamic/car.SetBrakeTorqueDistributionRL 0.4000000
audi-A4_Dynamic/car.SetBrakeTorqueDistributionRR 0.4000000
# Cruise control parameters for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetCruiseControlPosition 0
audi-A4_Dynamic/car.SetSpeedControl 0.0000000
audi-A4_Dynamic/car.SetSpeedLimit 50.0040000
# Trajectory parameters for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetLoop 1
audi-A4_Dynamic/car.SetCruiseControlPosition 0
audi-A4_Dynamic/car.SetSpeedControl 0.0000000
audi-A4_Dynamic/car.SetSpeedLimit 50.0040000
audi-A4_Dynamic/car.SetFileNameTrajectory 
audi-A4_Dynamic/car.SetExtensionTrajectory .trj
audi-A4_Dynamic/car.SetFileNameTrack 
audi-A4_Dynamic/car.SetExtensionTrack .trk
audi-A4_Dynamic/car.SetMode 0
audi-A4_Dynamic/car.SetSubMode 0
audi-A4_Dynamic/car.SetPeriod 0.0050000
audi-A4_Dynamic/car.SetOMGDDSEnabled false
audi-A4_Dynamic/car.SetCarDescriptionCommunicationMode 0
audi-A4_Dynamic/car.SetCarOrdersCommunicationMode 0
audi-A4_Dynamic/car.SetCarEnvironmentCommunicationMode 0
# Car dynamic model for audi-A4_Dynamic/car (0: Internal ; 1: External): 
audi-A4_Dynamic/car.SetModelSelector 0
# Car dynamic model for audi-A4_Dynamic/car, CarSim parameters (if used as External dynamic model): 
audi-A4_Dynamic/car.SetSimfileName simfile.sim
audi-A4_Dynamic/car.SetSimfileLocation C:/Workarea/ProSiVIC_DDS/bin/Win32.Debug/../../data/simfile/
audi-A4_Dynamic/car.SetSteerAngle 0.0000000
# Initials parameters for audi-A4_Dynamic/car: 
audi-A4_Dynamic/car.SetInitTrajectoryIndex 0
audi-A4_Dynamic/car.SetInitCurrentLoop 1
audi-A4_Dynamic/car.SetInitPosition 0.0000000 0.0000000 0.0000000
audi-A4_Dynamic/car.SetInitAngle 0.0000000 0.0000000 0.0000000
audi-A4_Dynamic/car.SetInitSpeed 0.0000000
audi-A4_Dynamic/car.SetInitSpeedControl 0.0000000
audi-A4_Dynamic/car.SetInitSpeedLimit 50.0040000
audi-A4_Dynamic/car.SetACCSpeed 0.0000000
audi-A4_Dynamic/car.SetPIDKp 100.0000000
audi-A4_Dynamic/car.SetPIDKi 0.7000000
audi-A4_Dynamic/car.SetPIDKd 0.0000000
audi-A4_Dynamic/car.SetLateralCorrectionTimeTarget 4.0000000
audi-A4_Dynamic/car.SetControlParameters 0.5000000 70.0000000 130.0000000 1.0000000 0.2000000

# Object radarLevel1 with type sivicPackage
radarLevel1.SetDisabled	0
radarLevel1.SetLocalPosition	-42.0000000 0.0000000 0.0000000
radarLevel1.SetLocalRotation	0.0000000 0.0000000 0.0000000
#radarLevel1.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
radarLevel1.SetLocalScale	1.0000000 1.0000000 1.0000000
radarLevel1.SetPackageData	RadarLevel1.zip

# Object radarLevel1/em with type sivicEMChannel
radarLevel1/em.SetPeriod 0.1000000
radarLevel1/em.SetOMGDDSEnabled false
radarLevel1/em.SetFileName em
radarLevel1/em.SetExtension .cap
radarLevel1/em.On 
radarLevel1/em.SetRecordEnabled false
radarLevel1/em.SetExportFormat tsv
radarLevel1/em.SetDisabled	0
radarLevel1/em.SetEmitter radarLevel1/radar
radarLevel1/em.SetReceiver radarLevel1/radar
radarLevel1/em.SetReceiverArea 1.0000000
radarLevel1/em.SetMaxBounces 1
radarLevel1/em.SetMaxNumPaths 10
radarLevel1/em.SetWaveVelocity 299792458.0000000
radarLevel1/em.SetTransmitterAxisConvention 0
radarLevel1/em.SetReceiverAxisConvention 0

# Object radarLevel1/radar with type sivicRadar
radarLevel1/radar.SetDisabled	0
radarLevel1/radar.SetLocalPosition	0.0000000 0.0000000 0.0000000
radarLevel1/radar.SetLocalRotation	0.0000000 0.0000000 0.0000000
#radarLevel1/radar.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
radarLevel1/radar.SetLocalScale	1.0000000 1.0000000 1.0000000
radarLevel1/radar.SetCollisionModel 
radarLevel1/radar.ClearLobes
radarLevel1/radar.AddLobe 1.0000000	0.0000000	1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
radarLevel1/radar.SetRCSData 
radarLevel1/radar.SetPolicy lobes
radarLevel1/radar.SetSymetryX none
radarLevel1/radar.SetSymetryY none
radarLevel1/radar.SetSymetryZ none
radarLevel1/radar.SetPeriod 0.1000000
radarLevel1/radar.SetOMGDDSEnabled true
radarLevel1/radar.SetFileName radar
radarLevel1/radar.SetExtension .cap
radarLevel1/radar.On 
radarLevel1/radar.SetRecordEnabled false
radarLevel1/radar.SetExportFormat tsv
radarLevel1/radar.SetPropagationChannel radarLevel1/em
radarLevel1/radar.SetAntennaType 1
radarLevel1/radar.SetModellingMode 0
radarLevel1/radar.SetComputationMode 1
radarLevel1/radar.SetDetectionMode 1
radarLevel1/radar.SetModulation 3
radarLevel1/radar.SetCarrierFrequency 76.5000000
radarLevel1/radar.SetBandWidth 300.0000000
radarLevel1/radar.SetSampleRate 40.0000000
radarLevel1/radar.SetPeriodDuration 0.0000100
radarLevel1/radar.SetChirpDuration 1.0000000
radarLevel1/radar.SetListenningDuration 0.0018000
radarLevel1/radar.SetThresholdDetection -500.0000000
radarLevel1/radar.SetAntennaMaxGain 24.0000000
radarLevel1/radar.SetAntennaStepAngle 0.5000000
radarLevel1/radar.SetAntennaOpenAngle 120.0000000
radarLevel1/radar.SetUseTracking 0
radarLevel1/radar.SetNbTargetsMax 16
radarLevel1/radar.SetFixSweepingGhostTargets 1
radarLevel1/radar.SetSweepingFixDistanceThreshold 1.0000000
radarLevel1/radar.SetSweepingFixAngleThreshold 5.0000000
radarLevel1/radar.SetSweepingFixSpeedThreshold 5.0000000

# Object radarLevel1/view with type sivicRadarViewport
radarLevel1/view.SetDisabled	0
radarLevel1/view.SetViewport 0 0 640 320
radarLevel1/view.SetRadar radarLevel1/radar
radarLevel1/view.SetViewingRange 100.0000000
radarLevel1/view.SetDisplayTargetWidth 1.0000000
radarLevel1/view.SetBackgroundColor 0.5000000 0.0000000 0.0000000 1.0000000
radarLevel1/view.SetAxisColor 0.7500000 0.7500000 0.7500000 1.0000000
radarLevel1/view.SetFontSize 12
radarLevel1/view.SetViewportOpacity 0.2500000
radarLevel1/view.SetDataColor 1.0000000 1.0000000 0.0000000 1.0000000
radarLevel1/view.SetAxisAngleStep 30.0000000
radarLevel1/view.SetAxisDistanceStep 25.0000000

# Object ground_checker with type sivicPackage
ground_checker.SetDisabled	0
ground_checker.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_checker.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_checker.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_checker.SetLocalScale	1.0000000 1.0000000 1.0000000
ground_checker.SetPackageData	Ground_checker.zip

# Object ground_checker/Ground_checker with type sivicBSPActor
ground_checker/Ground_checker.AddProperty	BaseSurfaceGrip	float	1
ground_checker/Ground_checker.AddProperty	ColorLabel	mgColor	255 153 255 255
ground_checker/Ground_checker.AddProperty	InfrastructureType	string	road
ground_checker/Ground_checker.AddProperty	layers	mgLayers	16777215
ground_checker/Ground_checker.SetDisabled	0
ground_checker/Ground_checker.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_checker/Ground_checker.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_checker/Ground_checker.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_checker/Ground_checker.SetLocalScale	1.0000000 1.0000000 1.0000000
ground_checker/Ground_checker.SetCastShadows	0
ground_checker/Ground_checker.SetRenderOrder	0.0000000
ground_checker/Ground_checker.SetDoNotRender	0
ground_checker/Ground_checker.SetBSPData Ground_checker.bsp
ground_checker/Ground_checker.SetRenderingDepth 8
ground_checker/Ground_checker.SetAmbientOcclusionMap 
ground_checker/Ground_checker.SetNearClippingDistance 0.0000000
ground_checker/Ground_checker.SetFarClippingDistance 



# Viewport ordering

editor/view.ToFront
audi-A4_Dynamic/vc.ToFront
radarLevel1/view.ToFront
