# Engine settings
clearcolorbuffer	1
clearcolor	0.0000000 0.0000000 0.0000000 0.0000000
ambient	1.0000000 1.0000000 1.0000000 0.0000000
fog	0
fogcolor	0.0000000 0.0000000 0.0000000 0.0000000
fogmode	exp
fogstart	100.0000000
fogend	500.0000000
fogdensity	1.0000000


# Object creation

new sivicDistanceObserverDisplay displaydistance
new sivicPackage audi
new sivicCarObserver carobs
new sivicObserverViewport carobsviewport
new sivicPackage ground_checker
new sivicTime time


# Object configuration

# Object _DefaultRenderer with type mgAccurateRenderer
_DefaultRenderer.SetDisabled	0
_DefaultRenderer.SetHidden	1
_DefaultRenderer.SetPersistent	1
_DefaultRenderer.SetWireframe 0
_DefaultRenderer.SetNoTextures 0
_DefaultRenderer.SetClampVertexColor 0
_DefaultRenderer.SetClampFragmentColor 0

# Object editor with type sivicPackage
editor.SetDisabled	0
editor.SetHidden	1
editor.SetPersistent	1
editor.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object editor/cam with type sivicCamera
editor/cam.SetPeriod 0.0400000
editor/cam.SetOMGDDSEnabled false
editor/cam.SetFileName cam
editor/cam.SetExtension .cap
editor/cam.Off 
editor/cam.SetRecordEnabled false
editor/cam.SetExportFormat tsv
editor/cam.SetDisabled	0
editor/cam.SetPersistent	1
editor/cam.SetLocalPosition	11.4572906 -44.4141731 45.4735947
editor/cam.SetLocalRotation	47.6545219 -18.4188213 -39.4992905
#editor/cam.SetLocalRotationAngles	49.9999809 -0.0000051 -42.2637520
editor/cam.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/cam.SetFrustum	-0.1233085 0.1233085 -0.0767327 0.0767327 0.1000000 5000.0000000
editor/cam.SetRenderSize 1104 687
editor/cam.SetRenderer editor/ren
editor/cam.SetCaptureFileName MGEngine
editor/cam.SetClearColorBufferRegion 1
editor/cam.SetColorFormat rgb8
editor/cam.SetDepthFormat DEPTH_24
editor/cam.SetMultiSamples 4
editor/cam.SetCorrectDistortion 1
editor/cam.SetEnableIntegration 0
editor/cam.SetExposureTime 0.0400000
editor/cam.SetExposureSampling 0.0050000
editor/cam.SetMatrixSize 2.6666000 2.0000000
editor/cam.SetFocalLength 1.3032253
editor/cam.SetZNear 0.1000000
editor/cam.SetZFar 5000.0000000
editor/cam.SetCollectDepthImage off
editor/cam.SetDepthImageRange 1000
editor/cam.SetDepthImageResolution 1
editor/cam.SetImageType RGB24
editor/cam.SetNbEffectiveBits 8
editor/cam.SetRecordFormat bmp
editor/cam.SetPNGCompression png_1
editor/cam.SetModeCorrection off
editor/cam.SetCollectLabelImage 0
editor/cam.SetOccludeLabels 1

# Object editor/view with type sivicCameraViewport
editor/view.SetDisabled	0
editor/view.SetPersistent	1
editor/view.SetAutoResize 1
editor/view.SetViewport 0.0000000% 0.0000000% 100.0000000% 100.0000000%
editor/view.SetCamera editor/cam
editor/view.SetColorMask 1 1 1
editor/view.SetForceCameraResize 1
editor/view.SetMinDepthRange 0.0000000
editor/view.SetMaxDepthRange 100.0000000
editor/view.SetLookupTexture 

# Object editor/ren with type sivicEditorRenderer
editor/ren.SetDisabled	0
editor/ren.SetPersistent	1
editor/ren.SetWireframe 0
editor/ren.SetNoTextures 0
editor/ren.SetClampVertexColor 0
editor/ren.SetClampFragmentColor 0
editor/ren.SetShowGrid 1
editor/ren.SetGridMesh checker
editor/ren.SetShowAxes 1
editor/ren.SetAxesMesh repere
editor/ren.SetHighlight 1
editor/ren.SetHighlightColor 1.0000000 0.3000000 0.0000000 

# Object editor/cont with type mgPositionController
editor/cont.SetDisabled	0
editor/cont.SetPersistent	1
editor/cont.AttachTo editor/cam
editor/cont.SetXPosController	x_trans3
editor/cont.SetYPosController	y_trans3
editor/cont.SetZPosController	z_trans3
editor/cont.SetXRotController	x_rot3
editor/cont.SetYRotController	y_rot3
editor/cont.SetZRotController	z_rot3
editor/cont.SetTranslationSpeed	10.0000000
editor/cont.SetRotationSpeed	3.1415899
editor/cont.SetRealTime	on
editor/cont.SetMode Fly

# Object editor/tt with type mgTrackTo
editor/tt.SetDisabled	0
editor/tt.SetPersistent	1
editor/tt.ApplyTo editor/cam

# Object editor/_RendererPlugin_sivicBeaconReceiverDisplay with type sivicBeaconReceiverDisplay
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicBeaconTransmitterDisplay with type sivicBeaconTransmitterDisplay
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCameraDisplay with type sivicCameraDisplay
editor/_RendererPlugin_sivicCameraDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCameraDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCameraDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCameraDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicCarDisplay with type sivicCarDisplay
editor/_RendererPlugin_sivicCarDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCarDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCarDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCarDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCarDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCarDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicCarDisplay.SetShowPath 1
editor/_RendererPlugin_sivicCarDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicCarDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetShowMeanTurningRadiusFront 0
editor/_RendererPlugin_sivicCarDisplay.SetShowTurningFrontDeadZone 0
editor/_RendererPlugin_sivicCarDisplay.SetShowCollisionRaytrace 0

# Object editor/_RendererPlugin_sivicCommunicationDisplay with type sivicCommunicationDisplay
editor/_RendererPlugin_sivicCommunicationDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetShowAll 0
editor/_RendererPlugin_sivicCommunicationDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCompassDisplay with type sivicCompassDisplay
editor/_RendererPlugin_sivicCompassDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassDisplay.SetWireframe 1
editor/_RendererPlugin_sivicCompassDisplay.SetShowWind 1

# Object editor/_RendererPlugin_sivicCompassRoseDisplay with type sivicCompassRoseDisplay
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetWireframe 0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetShowWind 1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCompassPoint 8

# Object editor/_RendererPlugin_sivicDistanceObserverDisplay with type sivicDistanceObserverDisplay
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetWireframe 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowObjectIndicator 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowMeasurePoint 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetColor 0.0000000 0.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLineWidth 5.0000000

# Object editor/_RendererPlugin_sivicEventDisplay with type sivicEventDisplay
editor/_RendererPlugin_sivicEventDisplay.SetDisabled	0
editor/_RendererPlugin_sivicEventDisplay.SetPersistent	1
editor/_RendererPlugin_sivicEventDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicEventDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicEventDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicEventDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicEventDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicEventDisplay.SetShowAll 0
editor/_RendererPlugin_sivicEventDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay with type sivicExternalTrajectoryReaderDisplay
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPrecision 8
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPathColor 1.0000000 0.3300000 0.5000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPath 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicGPSDisplay with type sivicGPSDisplay
editor/_RendererPlugin_sivicGPSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicGPSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicGPSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicGPSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicGPSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicGPSDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicHumanDisplay with type sivicHumanDisplay
editor/_RendererPlugin_sivicHumanDisplay.SetDisabled	0
editor/_RendererPlugin_sivicHumanDisplay.SetPersistent	1
editor/_RendererPlugin_sivicHumanDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicHumanDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowPath 1
editor/_RendererPlugin_sivicHumanDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicHumanDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetShowWalkingZone 0

# Object editor/_RendererPlugin_sivicInclinometerDisplay with type sivicInclinometerDisplay
editor/_RendererPlugin_sivicInclinometerDisplay.SetDisabled	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetPersistent	1
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicLightSourceDisplay with type sivicLightSourceDisplay
editor/_RendererPlugin_sivicLightSourceDisplay.SetDisabled	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetPersistent	1
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetShowAll 0
editor/_RendererPlugin_sivicLightSourceDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRadarHUD with type sivicRadarHUD
editor/_RendererPlugin_sivicRadarHUD.SetDisabled	0
editor/_RendererPlugin_sivicRadarHUD.SetPersistent	1
editor/_RendererPlugin_sivicRadarHUD.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarHUD.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarHUD.SetCastShadows	0
editor/_RendererPlugin_sivicRadarHUD.SetRenderOrder	5.0000000
editor/_RendererPlugin_sivicRadarHUD.SetDoNotRender	0
editor/_RendererPlugin_sivicRadarHUD.SetLobePlot 1
editor/_RendererPlugin_sivicRadarHUD.SetLogDisplay 1
editor/_RendererPlugin_sivicRadarHUD.SetDisplayResolution 1.0000000

# Object editor/_RendererPlugin_sivicRadarSimpleDisplay with type sivicRadarSimpleDisplay
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicRangefinderDisplay with type sivicRangefinderDisplay
editor/_RendererPlugin_sivicRangefinderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetShowAll 1
editor/_RendererPlugin_sivicRangefinderDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRCSDisplay with type sivicRCSDisplay
editor/_RendererPlugin_sivicRCSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRCSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRCSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRCSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRCSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicRCSDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicTrajectoryDisplay with type sivicTrajectoryDisplay
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDisabled	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPersistent	1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPrecision 8
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPathColor 0.2000000 0.6000000 0.5000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPath 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicUltrasonicSensorDisplay with type sivicUltrasonicSensorDisplay
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDisabled	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetPersistent	1
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDoNotRender	0

# Object displaydistance with type sivicDistanceObserverDisplay
displaydistance.SetDisabled	0
displaydistance.SetPersistent	1
displaydistance.SetLocalPosition	0.0000000 0.0000000 0.0000000
displaydistance.SetLocalRotation	0.0000000 0.0000000 0.0000000
#displaydistance.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
displaydistance.SetLocalScale	1.0000000 1.0000000 1.0000000
displaydistance.SetCastShadows	0
displaydistance.SetRenderOrder	4.0000000
displaydistance.SetDoNotRender	0
displaydistance.SetShowAll 0
displaydistance.SetWireframe 1
displaydistance.SetShowObjectIndicator 0
displaydistance.SetShowMeasurePoint 1
displaydistance.SetColor 0.0000000 0.0000000 1.0000000
displaydistance.SetLineWidth 5.0000000

# Object audi with type sivicPackage
audi.SetDisabled	0
audi.SetLocalPosition	0.0000000 0.0000000 0.0000000
audi.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi.SetLocalScale	1.0000000 1.0000000 1.0000000
audi.SetPackageData	Audi-A4_Dynamic.zip

# Object audi/vc with type sivicCarViewport
audi/vc.SetPeriod 0.0400000
audi/vc.SetOMGDDSEnabled false
audi/vc.SetFileName vc
audi/vc.SetExtension .cap
audi/vc.On 
audi/vc.SetRecordEnabled false
audi/vc.SetExportFormat tsv
audi/vc.SetDisabled	0
audi/vc.SetViewport 0 0 100 46
# Backgound color for audi/vc: 
audi/vc.SetTransparency true
audi/vc.SetWatermark 0.0000000
audi/vc.SetBackgroundColor 1.0000000 0.0000000 0.0000000 0.0000000
audi/vc.SetPosition 0 0
audi/vc.SetSize 100 46
audi/vc.SetDigitWidth 0.1500000
audi/vc.SetPositionUnit 0.6000000
audi/vc.SetDataColor 0.6980392 0.9607843 0.1254902 1.0000000
audi/vc.SetCar audi/car
audi/vc.SetDisplayAcceleration 1

# Object audi/chassis with type sivicMeshActor
audi/chassis.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/chassis.AddProperty	VehicleModel	string	Audi_A4
audi/chassis.AddProperty	VehicleType	string	car
audi/chassis.AddProperty	layers	mgLayers	16777215
audi/chassis.SetDisabled	0
audi/chassis.SetLocalPosition	-0.9267305 -0.0000242 0.2918077
audi/chassis.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi/chassis.SetLocalRotationAngles	-0.0025874 0.0003770 0.0000050
audi/chassis.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/chassis.SetCastShadows	0
audi/chassis.SetRenderOrder	1.0000000
audi/chassis.SetDoNotRender	0
audi/chassis.SetMesh	A4/A4_Dynamic
audi/chassis.SetCatchShadows	1
audi/chassis.SetOccludeAmbient	0
audi/chassis.SetCameraAligned	0
audi/chassis.OverrideMaterial	Body Body_Black

# Object audi/fl with type sivicMeshActor
audi/fl.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/fl.AddProperty	layers	mgLayers	16777215
audi/fl.SetDisabled	0
audi/fl.MakeChildOf audi/chassis
audi/fl.SetLocalPosition	2.6600018 0.7500115 -0.0210088
audi/fl.SetLocalRotation	0.0000000 29.1137810 0.0000000
#audi/fl.SetLocalRotationAngles	0.0000000 29.1137810 0.0000000
audi/fl.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/fl.SetCastShadows	0
audi/fl.SetRenderOrder	1.0000000
audi/fl.SetDoNotRender	0
audi/fl.SetMesh	A4_wheel/left_wheel
audi/fl.SetCatchShadows	1
audi/fl.SetOccludeAmbient	0
audi/fl.SetCameraAligned	0

# Object audi/fr with type sivicMeshActor
audi/fr.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/fr.AddProperty	layers	mgLayers	16777215
audi/fr.SetDisabled	0
audi/fr.MakeChildOf audi/chassis
audi/fr.SetLocalPosition	2.6600018 -0.7499885 -0.0210766
audi/fr.SetLocalRotation	-0.0000000 -26.2475986 -0.0000000
#audi/fr.SetLocalRotationAngles	0.0000000 -26.2475872 0.0000000
audi/fr.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/fr.SetCastShadows	0
audi/fr.SetRenderOrder	1.0000000
audi/fr.SetDoNotRender	0
audi/fr.SetMesh	A4_wheel/right_wheel
audi/fr.SetCatchShadows	1
audi/fr.SetOccludeAmbient	0
audi/fr.SetCameraAligned	0

# Object audi/rl with type sivicMeshActor
audi/rl.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/rl.AddProperty	layers	mgLayers	16777215
audi/rl.SetDisabled	0
audi/rl.MakeChildOf audi/chassis
audi/rl.SetLocalPosition	0.0000015 0.7500111 -0.0210263
audi/rl.SetLocalRotation	0.0000000 21.5699558 0.0000000
#audi/rl.SetLocalRotationAngles	0.0000000 21.5699654 0.0000000
audi/rl.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/rl.SetCastShadows	0
audi/rl.SetRenderOrder	1.0000000
audi/rl.SetDoNotRender	0
audi/rl.SetMesh	A4_wheel/left_wheel
audi/rl.SetCatchShadows	1
audi/rl.SetOccludeAmbient	0
audi/rl.SetCameraAligned	0

# Object audi/rr with type sivicMeshActor
audi/rr.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/rr.AddProperty	layers	mgLayers	16777215
audi/rr.SetDisabled	0
audi/rr.MakeChildOf audi/chassis
audi/rr.SetLocalPosition	0.0000017 -0.7499889 -0.0210941
audi/rr.SetLocalRotation	0.0000000 21.5954208 0.0000000
#audi/rr.SetLocalRotationAngles	0.0000000 21.5954361 0.0000000
audi/rr.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/rr.SetCastShadows	0
audi/rr.SetRenderOrder	1.0000000
audi/rr.SetDoNotRender	0
audi/rr.SetMesh	A4_wheel/right_wheel
audi/rr.SetCatchShadows	1
audi/rr.SetOccludeAmbient	0
audi/rr.SetCameraAligned	0

# Object audi/CollisionModel with type sivicMeshActor
audi/CollisionModel.AddProperty	layers	mgLayers	16777215
audi/CollisionModel.SetDisabled	0
audi/CollisionModel.MakeChildOf audi/chassis
audi/CollisionModel.SetLocalPosition	0.0000000 0.0000000 0.0000000
audi/CollisionModel.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi/CollisionModel.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
audi/CollisionModel.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/CollisionModel.SetCastShadows	0
audi/CollisionModel.SetRenderOrder	1.0000000
audi/CollisionModel.SetDoNotRender	1
audi/CollisionModel.SetMesh	audi_A4_rcs/audi_A4_rcs
audi/CollisionModel.SetCatchShadows	1
audi/CollisionModel.SetOccludeAmbient	0
audi/CollisionModel.SetCameraAligned	0

# Object audi/RCS with type sivicRCS
audi/RCS.SetDisabled	0
audi/RCS.MakeChildOf audi/chassis
audi/RCS.SetLocalPosition	1.5000000 0.0000000 0.0000000
audi/RCS.SetLocalRotation	0.0000000 0.0000000 0.0000000
#audi/RCS.SetLocalRotationAngles	0.0000000 0.0000000 0.0000000
audi/RCS.SetLocalScale	1.0000000 1.0000000 1.0000000
audi/RCS.SetCollisionModel audi/CollisionModel
audi/RCS.ClearLobes
audi/RCS.AddLobe 1.0000000	1.0000000	-1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 -1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 -1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
audi/RCS.SetRCSData biw_work3_monostatic.rcs
audi/RCS.SetPolicy table
audi/RCS.SetSymetryX none
audi/RCS.SetSymetryY none
audi/RCS.SetSymetryZ none

# Object audi/car with type sivicCar
audi/car.AddProperty	ColorLabel	mgColor	255 0 0 255
audi/car.SetDisabled	0
# SetCarDescriptionData will be use to load resource used to override car body color.
audi/car.SetCarBodyColorMaterialData body_color_material.conf
audi/car.SetCarBodyColor Black
# Meshes for audi/car: 
audi/car.SetChassis audi/chassis
audi/car.SetWheelFL audi/fl
audi/car.SetWheelFR audi/fr
audi/car.SetWheelRL audi/rl
audi/car.SetWheelRR audi/rr
audi/car.SetEnableWheelScale false
# Controllers for audi/car (analogical inputs): 
audi/car.SetAccCtrl car1_ThrottlePedal
audi/car.SetAccCtrlDuration 0.0001000
audi/car.SetClutchCtrl car1_ClutchPedal
audi/car.SetClutchCtrlDuration 0.0001000
audi/car.SetBrakeCtrl car1_BrakePedal
audi/car.SetBrakeCtrlDuration 0.0001000
audi/car.SetSteerCtrl car1_SteeringWheelAngle
audi/car.SetSteerCtrlDuration 0.0001000
# Controllers for audi/car (binary inputs): 
audi/car.SetUpGearCtrl car1_UpGear
audi/car.SetDownGearCtrl car1_DownGear
audi/car.SetUpKeyCtrl car1_UpKey
audi/car.SetDownKeyCtrl car1_DownKey
audi/car.SetStopCtrl car1_Stop
audi/car.SetUseAdaptativeSteeringSpeed 1
audi/car.SetUseRoadAsGround 1
audi/car.SetUseStopOnObstacles 1
audi/car.SetMass 1374.0000000
audi/car.SetWheelsSpacing 1.3300000 1.3300000 0.7500000 0.7500000
#audi/car.SetWheelbase 2.6600001
#audi/car.SetFrontTrack 1.5000000
#audi/car.SetRearTrack 1.5000000
audi/car.SetIgnitionKey 1
audi/car.SetGearShift 1
audi/car.SetAutoClutch 1
audi/car.SetPosition 0.4032709 -0.0000149 0.5625486
audi/car.SetAngle -0.0025874 0.0003770 0.0000050
audi/car.SetGroundTireAltitude 0.0000000 0.0000000 0.0000000 0.0000000
# Shock absorbers parameters for audi/car: 
audi/car.SetShockAbsorberFL 20000.0000000 6000.0000000
audi/car.SetShockAbsorberFR 20000.0000000 6000.0000000
audi/car.SetShockAbsorberRL 20000.0000000 6000.0000000
audi/car.SetShockAbsorberRR 20000.0000000 6000.0000000
# Wheels parameters for audi/car: 
audi/car.SetWheelsHeight 0.0400000 0.0300000
audi/car.SetTireCode 225.0000000 18.1102009 18.1102009
audi/car.SetTireGripFR 0.9000000
audi/car.SetTireGripFL 0.9000000
audi/car.SetTireGripRR 0.9000000
audi/car.SetTireGripRL 0.9000000
# Masses and inertia for audi/car: 
audi/car.SetCarMasses 1500.0000000 1500.0000000 1340.0000000
audi/car.SetCarMomentOfInertia 305.0000000 2000.0000000 2454.0000000
audi/car.SetTireMass 18.0000000
audi/car.SetTireMomentOfInertia 1.2825000
audi/car.SetMaxOrderAcc 790.0000000
audi/car.SetMaxOrderBrk 1250.0000000
audi/car.SetMaxOrderSteer 0.5200000
audi/car.SetMaxSpeedSteer 0.7853982
audi/car.SetBrakeTorqueDistributionFL 0.6000000
audi/car.SetBrakeTorqueDistributionFR 0.6000000
audi/car.SetBrakeTorqueDistributionRL 0.4000000
audi/car.SetBrakeTorqueDistributionRR 0.4000000
# Cruise control parameters for audi/car: 
audi/car.SetCruiseControlPosition 0
audi/car.SetSpeedControl 0.0000000
audi/car.SetSpeedLimit 50.0040000
# Trajectory parameters for audi/car: 
audi/car.SetLoop 1
audi/car.SetCruiseControlPosition 0
audi/car.SetSpeedControl 0.0000000
audi/car.SetSpeedLimit 50.0040000
audi/car.SetFileNameTrajectory 
audi/car.SetExtensionTrajectory .trj
audi/car.SetFileNameTrack 
audi/car.SetExtensionTrack .trk
audi/car.SetMode 0
audi/car.SetSubMode 0
audi/car.SetPeriod 0.0050000
audi/car.SetOMGDDSEnabled true
audi/car.SetCarDescriptionCommunicationMode 0
audi/car.SetCarOrdersCommunicationMode 3
audi/car.SetCarEnvironmentCommunicationMode 0
# Car dynamic model for audi/car (0: Internal ; 1: External): 
audi/car.SetModelSelector 0
# Car dynamic model for audi/car, CarSim parameters (if used as External dynamic model): 
audi/car.SetSimfileName simfile.sim
audi/car.SetSimfileLocation D:/ProSiVIC/bin/Win32.Debug/../../data/simfile/
audi/car.SetSteerAngle 0.0000000
# Initials parameters for audi/car: 
audi/car.SetInitTrajectoryIndex 0
audi/car.SetInitCurrentLoop 1
audi/car.SetInitPosition 0.0490238 -0.0000037 0.7998738
audi/car.SetInitAngle -0.0019432 0.0002829 0.0000050
audi/car.SetInitSpeed 0.0000000
audi/car.SetInitSpeedControl 0.0000000
audi/car.SetInitSpeedLimit 50.0040000
audi/car.SetACCSpeed 0.0000000
audi/car.SetPIDKp 1000.0000000
audi/car.SetPIDKi 0.7000000
audi/car.SetPIDKd 0.0000000
audi/car.SetLateralCorrectionTimeTarget 4.0000000
audi/car.SetControlParameters 0.5000000 70.0000000 130.0000000 1.0000000 0.2000000

# Object carobs with type sivicCarObserver
carobs.SetPeriod 0.0400000
carobs.SetOMGDDSEnabled false
carobs.SetFileName carobs
carobs.SetExtension .cap
carobs.On 
carobs.SetRecordEnabled false
carobs.SetExportFormat tsv
carobs.SetDisabled	0
carobs.SetPrecision 2
carobs.SetObject audi/car

# Object carobsviewport with type sivicObserverViewport
carobsviewport.SetDisabled	0
carobsviewport.SetViewport 0 213 1292 703
# Backgound color for carobsviewport: 
carobsviewport.SetTransparency true
carobsviewport.SetWatermark 0.1000000
carobsviewport.SetBackgroundColor 1.0000000 0.0000000 0.0000000 0.1000000
carobsviewport.SetCarObserver carobs
# SetTopViewMode is used to select mode: "SetTopView" or "GraphView": 
carobsviewport.SetTopViewMode 0
carobsviewport.SetTextColor 1.0000000 1.0000000 1.0000000 1.0000000
# GraphView parameters: 
carobsviewport.SetDisplay 0
carobsviewport.SetModeStrip 1
carobsviewport.SetGraphColor 1.0000000 1.0000000 0.0000000 0.7000000
carobsviewport.SetAxisColor 1.0000000 0.0000000 0.0000000 0.7000000
carobsviewport.SetTimeScale 20.0000000
carobsviewport.SetYAxisScale 50.0000000
# TopView parameters: 
carobsviewport.SetDispForceValue 0

# Object ground_checker with type sivicPackage
ground_checker.SetDisabled	0
ground_checker.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_checker.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_checker.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_checker.SetLocalScale	62.0000000 1.0000000 1.0000000
ground_checker.SetPackageData	Ground_checker.zip

# Object ground_checker/Ground_checker with type sivicBSPActor
ground_checker/Ground_checker.AddProperty	BaseSurfaceGrip	float	1
ground_checker/Ground_checker.AddProperty	ColorLabel	mgColor	255 153 255 255
ground_checker/Ground_checker.AddProperty	InfrastructureType	string	road
ground_checker/Ground_checker.AddProperty	layers	mgLayers	16777215
ground_checker/Ground_checker.SetDisabled	0
ground_checker/Ground_checker.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_checker/Ground_checker.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_checker/Ground_checker.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_checker/Ground_checker.SetLocalScale	1.0000000 1.0000000 1.0000000
ground_checker/Ground_checker.SetCastShadows	0
ground_checker/Ground_checker.SetRenderOrder	0.0000000
ground_checker/Ground_checker.SetDoNotRender	0
ground_checker/Ground_checker.SetBSPData Ground_checker.bsp
ground_checker/Ground_checker.SetRenderingDepth 8
ground_checker/Ground_checker.SetAmbientOcclusionMap 
ground_checker/Ground_checker.SetNearClippingDistance 0.0000000
ground_checker/Ground_checker.SetFarClippingDistance 

# Object time with type sivicTime
time.SetPeriod 0.0400000
time.SetOMGDDSEnabled false
time.SetFileName time
time.SetExtension .cap
time.Off 
time.SetRecordEnabled false
time.SetExportFormat tsv
time.SetDisabled	0
time.SetSynchro 0



# Viewport ordering

editor/view.ToFront
audi/vc.ToFront
carobsviewport.ToFront
